Upload Data

In [5]:
import pandas as pd

github_url = "https://raw.githubusercontent.com/DuaA-A/Enterprise-E-Commerce-Predictive-Analytics/main/DailySales%20(1).xlsx"

df = pd.read_excel(github_url)

print("Shape:", df.shape)
df.head()

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

Shape: (13324, 37)

,Date,Title,Account Title,Market Place,SKU,FNSKU,ASIN,Parent ASIN,Is Parent,Internal Name,...,Impressions,Clicks,PPC Orders,PPC Sales,PPC Cost,PPC Conv,OOE,Net Profit,Net Margin,Net ROI
0,2020-10-01,High Absorption Magnesium Citrate Supplements ...,[ UK ] Aava,UK,UK_Aava_Magnesium_400mg_120_05,X000JJIQ79,B01GU9QLZC,NaN,0.0,NaN,...,3423.0,13.0,2.0,29.36,-13.06,0.1538,0.0,56.28,0.1852,0.3142
1,2020-10-02,High Absorption Magnesium Citrate Supplements ...,[ UK ] Aava,UK,UK_Aava_Magnesium_400mg_120_05,X000JJIQ79,B01GU9QLZC,NaN,0.0,NaN,...,2786.0,7.0,0.0,0.00,-7.33,0.0000,0.0,71.73,0.2034,0.3439
2,2020-10-03,High Absorption Magnesium Citrate Supplements ...,[ UK ] Aava,UK,UK_Aava_Magnesium_400mg_120_05,X000JJIQ79,B01GU9QLZC,NaN,0.0,NaN,...,2927.0,7.0,1.0,14.69,-6.15,0.1429,0.0,61.37,0.1386,0.2416
3,2020-10-04,High Absorption Magnesium Citrate Supplements ...,[ UK ] Aava,UK,UK_Aava_Magnesium_400mg_120_05,X000JJIQ79,B01GU9QLZC,NaN,0.0,NaN,...,3584.0,16.0,2.0,44.07,-16.51,0.1250,0.0,39.49,0.1573,0.2684
4,2020-10-05,High Absorption Magnesium Citrate Supplements ...,[ UK ] Aava,UK,UK_Aava_Magnesium_400mg_120_05,X000JJIQ79,B01GU9QLZC,NaN,0.0,NaN,...,4329.0,7.0,0.0,0.00,-4.47,0.0000,0.0,59.86,0.2116,0.3588

Data Cleaning

In [6]:

print(df.info())
display(df.describe())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13324 entries, 0 to 13323
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              13323 non-null  datetime64[ns]
 1   Title             13233 non-null  object
 2   Account Title     13323 non-null  object
 3   Market Place      13323 non-null  object
 4   SKU               13323 non-null  object
 5   FNSKU             13323 non-null  object
 6   ASIN              13284 non-null  object
 7   Parent ASIN       2130 non-null   object
 8   Is Parent         13323 non-null  float64
 9   Internal Name     0 non-null      float64
 10  Brand             13233 non-null  object
 11  Product Group     0 non-null      float64
 12  Taxes             13323 non-null  float64
 13  Orders            13323 non-null  float64
 14  Units             13323 non-null  float64
 15  Refunded          13323 non-null  float64
 16  Refund %          13323 non-null  float64
 17  Unit Session %    13323 non-null  float64
 18  Promo Units       13323 non-null  float64
 19  Organic Units     13323 non-null  float64
 20  Per Unit Revenue  11996 non-null  float64
 21  Revenue           13324 non-null  float64
 22  COGS              13323 non-null  float64
 23  FBA Fees          13323 non-null  float64
 24  Promo Amount      13323 non-null  float64
 25  Sessions          13323 non-null  float64
 26  Page Views        13323 non-null  float64
 27  Impressions       13323 non-null  float64
 28  Clicks            13323 non-null  float64
 29  PPC Orders        13323 non-null  float64
 30  PPC Sales         13323 non-null  float64
 31  PPC Cost          13323 non-null  float64
 32  PPC Conv          13323 non-null  float64
 33  OOE               13323 non-null  float64
 34  Net Profit        13323 non-null  float64
 35  Net Margin        13323 non-null  float64
 36  Net ROI           13323 non-null  float64
dtypes: datetime64[ns](1), float64(28), object(8)
memory usage: 3.8+ MB
None

,Date,Is Parent,Internal Name,Product Group,Taxes,Orders,Units,Refunded,Refund %,Unit Session %,...,Impressions,Clicks,PPC Orders,PPC Sales,PPC Cost,PPC Conv,OOE,Net Profit,Net Margin,Net ROI
count,13323,13323.0,0.0,0.0,13323.000000,13323.000000,13323.000000,13323.000000,13323.000000,13323.000000,...,13323.000000,13323.000000,13323.000000,13323.000000,13323.000000,13323.000000,13323.0,13323.000000,1.332300e+04,13323.000000
mean,2021-01-14 19:40:48.907903488,0.0,NaN,NaN,-21.696464,11.346093,13.298581,0.258650,0.017083,0.134443,...,4165.734819,15.582376,2.331757,51.895073,-15.246775,0.144013,0.0,61.224216,2.414762e+11,0.294288
min,2020-10-01 00:00:00,0.0,NaN,NaN,-1168.650000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,-1064.850000,0.000000,0.0,-486.310000,-8.702340e+15,-2.940700
25%,2020-11-23 00:00:00,0.0,NaN,NaN,-25.190000,2.000000,3.000000,0.000000,0.000000,0.000000,...,537.000000,2.000000,0.000000,0.000000,-17.230000,0.000000,0.0,5.350000,7.945000e-02,0.115350
50%,2021-01-16 00:00:00,0.0,NaN,NaN,-9.460000,7.000000,8.000000,0.000000,0.000000,0.000000,...,1917.000000,7.000000,1.000000,18.170000,-6.330000,0.076900,0.0,24.960000,1.903000e-01,0.291900
75%,2021-03-09 00:00:00,0.0,NaN,NaN,-1.980000,14.000000,16.000000,0.000000,0.000000,0.250000,...,5036.500000,18.000000,3.000000,63.610000,-1.140000,0.200000,0.0,65.095000,2.651000e-01,0.439600
max,2021-04-27 00:00:00,0.0,NaN,NaN,0.000000,955.000000,975.000000,42.000000,1.055600,7.000000,...,121882.000000,713.000000,135.000000,2875.440000,0.000000,6.000000,0.0,2342.190000,1.191953e+16,2.695400
std,NaN,0.0,NaN,NaN,35.902825,16.978017,20.305648,1.237357,0.080636,0.221282,...,6593.383509,25.220657,4.106758,94.217849,26.139957,0.258420,0.0,110.080049,1.278643e+14,0.308586

Date                    1
Title                  91
Account Title           1
Market Place            1
SKU                     1
FNSKU                   1
ASIN                   40
Parent ASIN         11194
Is Parent               1
Internal Name       13324
Brand                  91
Product Group       13324
Taxes                   1
Orders                  1
Units                   1
Refunded                1
Refund %                1
Unit Session %          1
Promo Units             1
Organic Units           1
Per Unit Revenue     1328
Revenue                 0
COGS                    1
FBA Fees                1
Promo Amount            1
Sessions                1
Page Views              1
Impressions             1
Clicks                  1
PPC Orders              1
PPC Sales               1
PPC Cost                1
PPC Conv                1
OOE                     1
Net Profit              1
Net Margin              1
Net ROI                 1
dtype: int64

Remove Duplicates

In [7]:
print("Duplicate Rows:", df.duplicated().sum())

df = df.drop_duplicates()

print("Shape After Removing Duplicates:")
print(df.shape)

Duplicate Rows: 0
Shape After Removing Duplicates:
(13324, 37)

Inconsistent

In [8]:
text_cols = df.select_dtypes(include='object').columns

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

for col in text_cols:
    df[col] = df[col].str.title()

print("Inconsistent Values Fixed")

Inconsistent Values Fixed

Null

In [9]:

null_values = df.isnull().sum()

print(null_values[null_values > 0])

Date                    1
Is Parent               1
Internal Name       13324
Product Group       13324
Taxes                   1
Orders                  1
Units                   1
Refunded                1
Refund %                1
Unit Session %          1
Promo Units             1
Organic Units           1
Per Unit Revenue     1328
COGS                    1
FBA Fees                1
Promo Amount            1
Sessions                1
Page Views              1
Impressions             1
Clicks                  1
PPC Orders              1
PPC Sales               1
PPC Cost                1
PPC Conv                1
OOE                     1
Net Profit              1
Net Margin              1
Net ROI                 1
dtype: int64

Missing Data

In [10]:


numeric_cols = df.select_dtypes(include='number').columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

print("Missing Values Handled")

Missing Values Handled

Rename Columns

In [11]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

print(df.columns.tolist())

['date', 'title', 'account_title', 'market_place', 'sku', 'fnsku', 'asin', 'parent_asin', 'is_parent', 'internal_name', 'brand', 'product_group', 'taxes', 'orders', 'units', 'refunded', 'refund_%', 'unit_session_%', 'promo_units', 'organic_units', 'per_unit_revenue', 'revenue', 'cogs', 'fba_fees', 'promo_amount', 'sessions', 'page_views', 'impressions', 'clicks', 'ppc_orders', 'ppc_sales', 'ppc_cost', 'ppc_conv', 'ooe', 'net_profit', 'net_margin', 'net_roi']

Standardization

In [12]:
for col in df.columns:
    if "date" in col.lower():
        df[col] = pd.to_datetime(df[col], errors='coerce')

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

print("Standardization Completed")

Standardization Completed

Save Silver Layer

In [13]:
output_file = "DailySales_Silver.xlsx"

df.to_excel(output_file, index=False)

print("Silver Layer Saved Successfully")

Silver Layer Saved Successfully

Download Data

In [14]:
from google.colab import files

files.download("DailySales_Silver.xlsx")